### ISSUE TITLE
use travis instead of gitlab-ci

### ISSUE THREAD

**Issue by job** [ypconfig/ypconfig#1]
The `.gitlab-ci.yml` file should be rewritten to a `.travis.yml` file

**Comment by WilliamDEdwards** [comment]
I feel like GitHub Actions is preferred to Travis CI nowadays. Perhaps https://github.com/ypconfig/ypconfig/issues/18 should supersede this issue.

**Comment by WilliamDEdwards** [comment]
> Perhaps https://github.com/ypconfig/ypconfig/issues/18 should supersede this issue.

It will.
